<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0.1 (Python 3.9.12 on darwin)" generated="20230302 12:08:38.741" rpa="false" schemaversion="3">
<suite id="s1" name="SampleTestCase" source="/Users/leonwee/Desktop/ndispcp-auto-testing-pom/SPA/Robot-files/pCloudy-Automation/Projects/RobotDataFiles/SampleTestCase.robot">
<test id="s1-t1" name="Open Test Application" line="11">
<kw name="Log To Console" library="BuiltIn">
<arg>${apiKey}</arg>
<doc>Logs the given message to the console.</doc>
<status status="PASS" starttime="20230302 12:08:38.914" endtime="20230302 12:08:38.914"/>
</kw>
<kw name="Open Application" library="AppiumLibrary">
<arg>${remotePath}</arg>
<arg>pCloudy_Username=${emailId}</arg>
<arg>pCloudy_ApiKey=${apiKey}</arg>
<arg>platformName=android</arg>
<arg>deviceName=${deviceId}</arg>
<arg>pCloudy_ApplicationName=${buildfullname}</arg>
<arg>pCloudy_DeviceFullName=${devicefullname}</arg>
<arg>newCommandTimeout=600</arg>
<arg>appPackage=com.example.android.testing.unittesting.BasicSample</arg>
<arg>appActivity=com.example.android.testing.unittesting.BasicSample.MainActivity</arg>
<arg>automationName=UiAutomator2</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |</doc>
<msg timestamp="20230302 12:08:39.058" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /appium/hubble/rmfbjsbbkr88-461448/wd/hub/session</msg>
<msg timestamp="20230302 12:08:39.319" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /appium/hubble/rmfbjsbbkr88-461448/wd/hub/session</msg>
<msg timestamp="20230302 12:08:39.564" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /appium/hubble/rmfbjsbbkr88-461448/wd/hub/session</msg>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20230302 12:08:39.822" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20230302 12:08:39.819" endtime="20230302 12:08:39.834"/>
</kw>
<msg timestamp="20230302 12:08:39.835" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20230302 12:08:39.836" level="FAIL">MaxRetryError: HTTPSConnectionPool(host='device.pcloudy.com', port=443): Max retries exceeded with url: /appium/hubble/rmfbjsbbkr88-461448/wd/hub/session (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))</msg>
<status status="FAIL" starttime="20230302 12:08:38.914" endtime="20230302 12:08:39.836"/>
</kw>
<status status="FAIL" starttime="20230302 12:08:38.914" endtime="20230302 12:08:39.837">MaxRetryError: HTTPSConnectionPool(host='device.pcloudy.com', port=443): Max retries exceeded with url: /appium/hubble/rmfbjsbbkr88-461448/wd/hub/session (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))</status>
</test>
<test id="s1-t2" name="DesiredCapabilities capabilities = new DesiredCapabilities();" line="20">
<status status="FAIL" starttime="20230302 12:08:39.837" endtime="20230302 12:08:39.838">Test contains no keywords.</status>
</test>
<test id="s1-t3" name="capabilities.setCapability(&quot;pCloudy_Username&quot;, &quot;Enter your email-id&quot;);" line="21">
<status status="FAIL" starttime="20230302 12:08:39.838" endtime="20230302 12:08:39.838">Test contains no keywords.</status>
</test>
<test id="s1-t4" name="capabilities.setCapability(&quot;pCloudy_ApiKey&quot;, &quot;Enter your APIKey&quot;);" line="22">
<status status="FAIL" starttime="20230302 12:08:39.839" endtime="20230302 12:08:39.839">Test contains no keywords.</status>
</test>
<test id="s1-t5" name="capabilities.setCapability(&quot;pCloudy_DurationInMinutes&quot;, 5);" line="23">
<status status="FAIL" starttime="20230302 12:08:39.840" endtime="20230302 12:08:39.840">Test contains no keywords.</status>
</test>
<test id="s1-t6" name="capabilities.setCapability(&quot;pCloudy_DeviceManafacturer&quot;, &quot;Samsung&quot;);" line="24">
<status status="FAIL" starttime="20230302 12:08:39.840" endtime="20230302 12:08:39.841">Test contains no keywords.</status>
</test>
<test id="s1-t7" name="capabilities.setBrowserName(&quot;Chrome&quot;);" line="25">
<status status="FAIL" starttime="20230302 12:08:39.841" endtime="20230302 12:08:39.841">Test contains no keywords.</status>
</test>
<test id="s1-t8" name="driver = new AndroidDriver(new URL(&quot;https://device.pcloudy.com/appiumcloud/wd/hub&quot;), capabilities);" line="26">
<status status="FAIL" starttime="20230302 12:08:39.842" endtime="20230302 12:08:39.842">Test contains no keywords.</status>
</test>
<status status="FAIL" starttime="20230302 12:08:38.742" endtime="20230302 12:08:39.843"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="8" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="8" skip="0" id="s1" name="SampleTestCase">SampleTestCase</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230302 12:08:39.058" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /appium/hubble/rmfbjsbbkr88-461448/wd/hub/session</msg>
<msg timestamp="20230302 12:08:39.319" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /appium/hubble/rmfbjsbbkr88-461448/wd/hub/session</msg>
<msg timestamp="20230302 12:08:39.564" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /appium/hubble/rmfbjsbbkr88-461448/wd/hub/session</msg>
<msg timestamp="20230302 12:08:39.835" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
